### ISSUE TITLE
[Feature Request]Will gpt-crawler support puppeteer ? 

### ISSUE THREAD

**Issue by yujinqiu** [BuilderIO/gpt-crawler#42]
Hi there,
I try to setup this project on Fedora 38, and it failed because of  playwright only support ubuntu and debian.
https://github.com/microsoft/playwright/issues/27890
It will be great if gpt-crawler can  also support  puppeteer, so it can run on more os distribution.

**Comment by buithehien1991** [comment]
@yujinqiu Crawler is crawlee, it also support for puppeteer, please see it: https://crawlee.dev/api/puppeteer-crawler 
You should fork to your repo and update it

If have time, please goto my GPT store with 15k GPTs: https://gptcombo.com/

**Comment by GoodVincentTu** [comment]
@yujinqiu I also tried to set it up, and this is a workaround solution. 
instead of installing the package using this command `npx playwright install`, try the following command:
```shell
sudo dnf install atk at-spi2-atk cups-libs libdrm at-spi2-core libX11 libXcomposite libXdamage libXext libXfixes libXrandr libgbm libxcb libxkbcommon pango cairo alsa-lib
```

I use the `1.42.1` for the playwright and fedora server as well, after executing the above command, the library works fine now. I hope it helps.
